### ISSUE TITLE
Update to search for new Lioranboard 2 app.

### ISSUE THREAD

**Issue by bweagle** [Teravus/LioranBoard-PC-Tablet-Input-Helper#1]
I noticed this is only looking for the original version of LioranBoard. You might want to update it to also look for the new (v2) version of LioranBoard.

**Comment by Teravus** [comment]
Good Idea

**Comment by Teravus** [comment]
Thanks for opening this issue!  

This issue has been resolved in the latest version.
https://github.com/Teravus/LioranBoard-PC-Tablet-Input-Helper/releases/tag/v1.0.1

It first looks for version 2, then, if It didn't find version 2..  It looks for version 1.
